# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

# This workflow checks that the BUSL license is not mentioned anywhere in
# a PR targeting a release that should maintain the MPL-2.0 license.
name: License Checker

on:
  pull_request:
    # Logic to only apply check 1.1[4,5,6].x branches is in license_checker.sh
    types: [opened, synchronize]

jobs:
  # checks that the diff does not contain any reference to
  # the BUSL license and thus retains the MPL-2.0 license
  license-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0 # by default the checkout action doesn't checkout all branches
      - name: Check for BUSL text in diff
        run: ./.github/scripts/license_checker.sh
